//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Big.Unicentro.Unipolla.DataAccess.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbUnicentroCRMEntities : DbContext
    {
        public dbUnicentroCRMEntities()
            : base("name=dbUnicentroCRMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UC_CUSTOMER> UC_CUSTOMER { get; set; }
        public virtual DbSet<UC_EMPLOYEE> UC_EMPLOYEE { get; set; }
        public virtual DbSet<UNIPOLLA_CODES_WINNER> UNIPOLLA_CODES_WINNER { get; set; }
        public virtual DbSet<UNIPOLLA_BET> UNIPOLLA_BET { get; set; }
        public virtual DbSet<UNIPOLLA_MATCH> UNIPOLLA_MATCH { get; set; }
        public virtual DbSet<UNIPOLLA_TEAM> UNIPOLLA_TEAM { get; set; }
        public virtual DbSet<UNIPOLLA_CODES> UNIPOLLA_CODES { get; set; }
        public virtual DbSet<UNIPOLLA_TOURNAMENT> UNIPOLLA_TOURNAMENT { get; set; }
    }
}
