//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Big.Unicentro.Unipolla.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNIPOLLA_BET
    {
        public int ID_BET { get; set; }
        public string ID_CODES_WINNER { get; set; }
        public int ID_MATCH { get; set; }
        public int ID_TEAM_1 { get; set; }
        public int ID_TEAM_2 { get; set; }
        public System.DateTime REGISTER_DATE_MATCH { get; set; }
        public Nullable<int> POINTS_TEAM_1 { get; set; }
        public Nullable<int> POINTS_TEAM_2 { get; set; }
        public Nullable<int> REGISTER_DATE_POINTS { get; set; }
    
        public virtual UNIPOLLA_CODES_WINNER UNIPOLLA_CODES_WINNER { get; set; }
        public virtual UNIPOLLA_MATCH UNIPOLLA_MATCH { get; set; }
        public virtual UNIPOLLA_TEAM UNIPOLLA_TEAM { get; set; }
        public virtual UNIPOLLA_TEAM UNIPOLLA_TEAM1 { get; set; }
    }
}
