//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Big.Unicentro.Unipolla.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNIPOLLA_CODES
    {
        public string GUID { get; set; }
        public decimal ID { get; set; }
        public string DESCRIPTION { get; set; }
        public bool ACTIVE { get; set; }
        public string ROL { get; set; }
    }
}
