//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Big.Unicentro.Unipolla.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNIPOLLA_CODES_WINNER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UNIPOLLA_CODES_WINNER()
        {
            this.UNIPOLLA_BET = new HashSet<UNIPOLLA_BET>();
        }
    
        public string GUID { get; set; }
        public decimal ID { get; set; }
        public string ID_EVENT { get; set; }
        public string ID_CLIENTE { get; set; }
        public System.DateTime REGISTER_DATE { get; set; }
        public bool IS_ACTIVE { get; set; }
        public decimal CODE_ID { get; set; }
        public string EMPLOYEE_ID { get; set; }
    
        public virtual UC_CUSTOMER UC_CUSTOMER { get; set; }
        public virtual UC_EMPLOYEE UC_EMPLOYEE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UNIPOLLA_BET> UNIPOLLA_BET { get; set; }
    }
}
