//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Big.Unicentro.Unipolla.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNIPOLLA_TEAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UNIPOLLA_TEAM()
        {
            this.UNIPOLLA_BET = new HashSet<UNIPOLLA_BET>();
            this.UNIPOLLA_BET1 = new HashSet<UNIPOLLA_BET>();
            this.UNIPOLLA_MATCH = new HashSet<UNIPOLLA_MATCH>();
            this.UNIPOLLA_MATCH1 = new HashSet<UNIPOLLA_MATCH>();
            this.UNIPOLLA_MATCH2 = new HashSet<UNIPOLLA_MATCH>();
        }
    
        public int ID_TEAM { get; set; }
        public string NAME_TEAM { get; set; }
        public string LOGO_TEAM { get; set; }
        public string ABBREVIATION { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public string GROUP_TEAM { get; set; }
        public Nullable<int> ID_TOURNAMENT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UNIPOLLA_BET> UNIPOLLA_BET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UNIPOLLA_BET> UNIPOLLA_BET1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UNIPOLLA_MATCH> UNIPOLLA_MATCH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UNIPOLLA_MATCH> UNIPOLLA_MATCH1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UNIPOLLA_MATCH> UNIPOLLA_MATCH2 { get; set; }
    }
}
