//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Big.Unicentro.Unipolla.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNIPOLLA_TOURNAMENT
    {
        public int ID_TOURNAMENT { get; set; }
        public string NAME_TOURNAMENT { get; set; }
        public Nullable<System.DateTime> REGISTRATION_DEADLINE { get; set; }
        public bool ACTIVE_TOURNAMENT { get; set; }
    }
}
